name: Build and Push Docker Image

on:
  push:
    tags:
      - 'release/v*.*.*'

jobs:
  build:
    runs-on: [ "self-hosted" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: plyoox-bot
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
